# The URL the site will be built for
base_url = "https://ordinobsolete.fr"

# The default language; used in feeds.
default_language = "en"

# Title
title = "Ordinobsolete"

[extra]
github  = "https://github.com/ordinobsolete/mycollection"