# The URL the site will be built for
base_url = "https://ordinobsolete.fr"

# The default language; used in feeds.
default_language = "en"

# Title
title = "Ordinobsolete"

[markdown]
render_emoji = true
smart_punctuation = true

[extra]
github = "https://github.com/ordinobsolete/mycollection"
issues = "https://github.com/ordinobsolete/mycollection/issues"