# Usage:
#
# ansible-playbook -i 'ordinobsolete.fr,' -u root deploy.yaml
#
---
- name: Publish ordinobsolete.fr
  hosts: 'ordinobsolete.fr'
  gather_facts: false

  vars:
    local_path: 'public/'
    remote_path: '/var/www/html/ordinobsolete.fr/'

  tasks:
    - name: Ensure static website is locally Built
      ansible.builtin.shell: >
        podman run
        --userns=keep-id
        -u "$(id -u):$(id -g)"
        -v $PWD:/app
        --workdir /app
        ghcr.io/getzola/zola:v0.19.2
        build
      delegate_to: localhost
      tags:
        - build

    - name: Ensure website is remotely Deployed
      ansible.posix.synchronize:
        src: "{{ local_path }}"
        dest: "{{ remote_path }}"
        archive: true
        delete: true
        recursive: true
      tags:
        - deploy

    - name: Enforce permissions
      ansible.builtin.file:
        path: "{{ remote_path }}"
        owner: wwwrun
        group: root
        mode: u=rx,g=rx,o=r
        recurse: true
      tags:
        - permissions

    - name: Ensure website is Online
      ansible.builtin.uri:
        url: 'https://ordinobsolete.fr'
        return_content: true
      register: http_response
      failed_when: "'Ordinobsolete' not in http_response.content"
      tags:
        - healthcheck
